sudo: required

language: ruby

services:
  - docker

before_script:
  - git clone --depth 1 https://github.com/WeblateOrg/docker.git

script:
  - docker build -t weblate/weblate:latest .
  - cd docker
  - docker-compose run --rm weblate migrate --noinput
  - docker-compose run --rm weblate collectstatic --noinput
  - docker-compose run --rm weblate createadmin
  - docker-compose run -e WEBLATE_LOGLEVEL=CRITICAL --rm weblate test --noinput weblate.accounts weblate.trans weblate.lang weblate.api weblate.gitexport weblate.screenshots weblate.utils
  - docker-compose start
  - docker-compose stop
  - docker-compose start
  - docker-compose stop
