sudo: true

language: python

env:
  global:
    - DOCKER_VERSION=1.7.1
    - SKIP_BRANCH_CHECKING=yes
    - UML_FIG=0
  matrix:
    - DB=mysql:5.6
    - DB=mariadb:10.0
    - DB=postgres:9.4
    - DB=busybox

install:
  # Install https://github.com/moul/travis-docker toolchain
  - curl -sLo - http://j.mp/install-travis-docker | sed 's/COMPOSE_VERSION=1.2.0/COMPOSE_VERSION=1.4.0/' | sh -xe

script:
  - sed -i "s/mariadb:10.0/$DB/" docker-compose.yml
  - if [ "$DB" = busybox ] ; then sed -i '/^  links:/,+1 d' docker-compose.yml ; fi
  - ./run 'docker-compose build && docker-compose run -u weblate weblate-web test -v 2 --noinput weblate.accounts weblate.trans.tests.test_views weblate.lang'
