sudo: required

language: ruby

services:
  - docker

before_script:
  - git clone --depth 1 https://github.com/WeblateOrg/docker.git

script:
  - docker build -t weblate/weblate:latest . || travis_terminate 1
  - cd docker
  - ./test.sh

addons:
  apt:
    packages:
      - docker-ce
