sudo: true

language: python

env:
  global:
    - DOCKER_VERSION=1.7.1
    - SKIP_BRANCH_CHECKING=yes

install:
  # Install https://github.com/moul/travis-docker toolchain
  - curl -sLo - http://j.mp/install-travis-docker | sed 's/COMPOSE_VERSION=1.2.0/COMPOSE_VERSION=1.4.0/' | sh -xe

script:
  - ./run 'docker-compose build && docker-compose run -u weblate weblate-web /app/bin/django-admin test || ls -la /app/data'
