sudo: required

services:
  - docker

language: python

env:
  matrix:
    - DB=mysql:5.6
    - DB=mariadb:10.0
    - DB=postgres:9.4
    - DB=busybox

matrix:
  allow_failures:
    # MariaDB dies for some reason when deleting database
    - env: DB=mariadb:10.0

script:
  - sed -i "s/postgres:9.4/$DB/" docker-compose.yml
  - if [ "$DB" = busybox ] ; then sed -i '/^  links:/,+1 d' docker-compose.yml ; fi
  - docker-compose build
  - docker-compose run -u weblate weblate-web test -v 2 --keepdb --noinput weblate.accounts weblate.trans.tests.test_views weblate.lang
