sudo: required

before_install:
  - docker-compose/.travis-update-docker-compose

services:
  - docker

script:
  - docker build -t weblate/weblate:latest . || travis_terminate 1
  - cd docker-compose
  - ./test.sh

addons:
  apt:
    packages:
      - docker-ce
