sudo: required

language: python

services:
  - docker

before_script:
  - docker-compose build

script:
  - docker-compose run --rm weblate migrate --noinput
  - docker-compose run --rm weblate collectstatic --noinput
  - docker-compose run --rm weblate createadmin
  - docker-compose run -e WEBLATE_LOGLEVEL=CRITICAL -e DJANGO_SETTINGS_MODULE=weblate.settings_example --rm weblate test --noinput weblate.accounts weblate.trans weblate.lang weblate.api weblate.gitexport weblate.screenshots weblate.utils weblate
  - docker-compose start
  - docker-compose stop
  - docker-compose start
  - docker-compose stop
