sudo: required

env:
  matrix:
    - DEBUG=1
    - DEBUG=0
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

before_script:
  - git clone --depth 1 https://github.com/WeblateOrg/docker-compose.git

jobs:
  include:
    - stage: build
      script:
      - docker build -t weblate/weblate:latest .
    - stage: test
      script: export DEBUG=0; ./test.sh
    - script: export DEBUG=1; ./test.sh

addons:
  apt:
    packages:
      - docker-ce
