version: '2'
services:
  weblate:
    build: weblate
    links:
      - database
      - cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./weblate/environment
  web:
    build: nginx
    links:
      - weblate
    ports:
      - "8000:80"
    volumes_from:
      - weblate:ro
  database:
    image: postgres:9.4
    env_file:
      - ./weblate/environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
  cache:
      image: memcached:1.4
volumes:
  weblate-data: {}
  postgres-data: {}