weblate-web:
  build: weblate-web
  links:
    - weblate-db
  ports:
    - "8000:8000"
  volumes:
    - /app/etc
    - /app/data
weblate-db:
  image: mariadb:10.0
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=weblate
    - MYSQL_USER=weblate
    - MYSQL_PASSWORD=weblate
    - MYSQL_DATABASE=weblatedb
  volumes_from:
    - /var/lib/mysql
