name: Docker Image CI

on: [push, pull_request]

jobs:

  regular:

    runs-on: ubuntu-latest
    name: Test

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag weblate/weblate:latest
    - name: Test the Docker image
      run: |
        cd docker-compose
        ./test.sh

  ssl:

    runs-on: ubuntu-latest
    name: Test with SSL

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag weblate/weblate:latest
    - name: Test the Docker image with SSL
      run: |
        VOLUMEPATH=$(docker volume inspect -f '{{.Mountpoint}}' wl_weblate-data)
        sudo mkdir -p $VOLUMEPATH/ssl
        sudo openssl req -x509 -nodes -days 365 -subj "/CN=weblate.example.com" -newkey rsa:2048 -keyout $VOLUMEPATH/ssl/privkey.pem -out $VOLUMEPATH/ssl/fullchain.pem
        sudo chown -R 1000:1000 $VOLUMEPATH/ssl
        cd docker-compose
        ./test.sh 4443 https
