name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag weblate/weblate:latest
    - name: Test the Docker image
      run: |
        cd docker-compose
        ./test.sh
    - name: Test the Docker image with SSL
      run: |
        VOLUMEPATH=$(docker volume inspect -f '{{.Mountpoint}}' wl_weblate-data)
        sudo mkdir -p $VOLUMEPATH/ssl
        sudo openssl req -x509 -nodes -days 365 -subj "/CN=weblate.example.com" -newkey rsa:2048 -keyout $VOLUMEPATH/ssl/privkey.pem -out $VOLUMEPATH/ssl/fullchain.pem
        sudo chown -R 1000:1000 $VOLUMEPATH/ssl
        ./test.sh 4443 https no
