name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag weblate/weblate:latest
    - name: Test the Docker image
      run: |
        cd docker-compose && ./test.sh
